### Home Route
GET http://localhost:4000/

###

### Register User
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "name": "Laasya",
  "email": "laasya@gmail.com",
  "password": "123456"
}

###

### Login User
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "laasya@gmail.com",
  "password": "123456"
}

###

### Add Customer
POST http://localhost:4000/customers/add-customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

{
  "name": "Sindhu",
  "phone": "8309552163",
  "address": "Hyderabad"
}

###

### Get All Customers
GET http://localhost:4000/customers/all-customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

###

### Add Transaction
POST http://localhost:4000/transactions/add-transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

{
  "customerId": "6a2e7f761daa256d242d2b36",
  "amount": 1000,
  "type": "debit",
  "note": "Pending Amount",
  "paymentMethod": "cash"
}

###

### Get All Transactions
GET http://localhost:4000/transactions/all-transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

###

### Dashboard Analytics
GET http://localhost:4000/analytics/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

###

### Send Reminder SMS
POST http://localhost:4000/reminder/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTJiZjkyNmZkYzQzOGRiOGQ3YmI2NjgiLCJlbWFpbCI6ImxhYXN5YUBnbWFpbC5jb20iLCJpYXQiOjE3ODE0MzIxNDQsImV4cCI6MTc4MTUxODU0NH0.7l89hAXqbqtVqKhK1SZX44Fx7JH0hh5mDEcKj2jtd9E

{
  "phone": "8309552163",
  "name": "Sindhu",
  "balance": 1000
}